# Generated by Django 2.1 on 2018-10-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='img',
            field=models.CharField(max_length=110),
        ),
    ]
